spring:
  datasource:
    db-type: "mysql"  # mysql or oracle

    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/TEST
      username: root
      password: root
    oracle:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      username: admin
      password: admin
  jpa:
    database: ${spring.datasource.db-type}
    database-platform: ${spring.jpa.properties.hibernate.dialect.${spring.datasource.db-type}}
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        show_sql: true
        cache:
          use_query_cache: false
        dialect:
          #  mysql: org.hibernate.dialect.MySQLDialect
          mysql: org.example.example2.config.CustomMySQLDialect
          oracle: org.hibernate.dialect.OracleDialect
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace