name: Pull request

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-and-analyze:
    name: Test and analyze
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g -XX:MaxMetaspaceSize=512m' -Dorg.gradle.parallel=true"
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name : Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle
      - name : Run tests
        run: |
          ./gradlew test
          


